name: Deploy to WordPress.org

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    tag:
        name: New release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build
              run: |
                  npm install
                  npm run production
            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: true
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            - name: Create zip archive
              run: |
                git archive --format=zip HEAD -o ${{ github.event.repository.name }}.zip
                mkdir ${{ github.event.repository.name }}
                unzip ${{ github.event.repository.name }}.zip -d ${{ github.event.repository.name }}
                rm ${{ github.event.repository.name }}.zip
                cp -r dist ${{ github.event.repository.name }}
                zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  ${{ github.event.repository.name }}.zip